name: Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2 
      - name: Deploy in EC2
        env:
            PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY  }}
            HOSTNAME : ${{ secrets.HOST_NAME  }}
            USER_NAME : ${{ secrets.HOST_USERNAME  }}
            
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME}
          
            #Now we have got the access of EC2 and we will start the deploy .
            cd ~/projects/react-with-docker/ &&     
            sudo docker build . -t react-with-docker-image &&
            sudo docker stop react-with-docker-container &&
            sudo docker run -it --rm -p 3000:3000 -d --name react-with-docker-container react-with-docker-image
